[package]
name = "reviews"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]

[dependencies]
actix-web = { git = "https://github.com/actix/actix-web" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
log = "0.4"
env_logger = "0.5"
